### ISSUE TITLE
isBlank

### ISSUE THREAD

**Issue by Pluto1219** [omar-hanafy/dart_helper_utils#1]
First and foremost, I would like to extend my heartfelt gratitude for the exceptional tool you have provided. It has been an invaluable asset to me.

In this spirit, I would like to humbly propose a suggestion to further enhance the tool's capabilities. Due to my personal experience with obsessive-compulsive disorder, I recommend adding an isBlank method to complement the existing isNotBlank method. This addition would provide a more comprehensive and versatile approach to string evaluation, catering to a wider range of use cases.

**Comment by omar-hanafy** [comment]
You’re correct, I might have forgotten to include the isBlank method. I’ve now added it. The isBlank method is an alias for isEmptyOrNull, so both perform the same function: checking if the string is null, empty, or solely made of whitespace characters or empty lines.
will release a version (1.1.0) soon with multiple enhancements. Thanks!

**Comment by Pluto1219** [comment]
Thank you very much
